//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zelentsov_eyes
{
    using System;
    using System.Collections.Generic;

    public partial class ProductSale
    {
        public int ID { get; set; }
        public int AgentID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime SaleDate { get; set; }
        public string Date
        {
            get
            {
                return (string)this.SaleDate.ToShortDateString();
            }
        }
        public int ProductCount { get; set; }
        public string Name
        {
            get
            {
                return Product.Title;
            }
        }
        public virtual Agent Agent { get; set; }
        public virtual Product Product { get; set; }
    }
}
